config/routes.rb
Rails.application.routes.draw do
  resources :firstnames
  resources :surnames
  resources :languages
  resources :cities
  resources :countries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/firstname.rb
class Firstname < ApplicationRecord
  belongs_to :language
end

app/controllers/firstnames_controller.rb
class FirstnamesController < ApplicationController
  before_action :set_firstname, only: [:show, :edit, :update, :destroy]

  # GET /firstnames
  # GET /firstnames.json
  def index
    @firstnames = Firstname.all
  end

  # GET /firstnames/1
  # GET /firstnames/1.json
  def show
  end

  # GET /firstnames/new
  def new
    @firstname = Firstname.new
  end

  # GET /firstnames/1/edit
  def edit
  end

  # POST /firstnames
  # POST /firstnames.json
  def create
    @firstname = Firstname.new(firstname_params)

    respond_to do |format|
      if @firstname.save
        format.html { redirect_to @firstname, notice: 'Firstname was successfully created.' }
        format.json { render :show, status: :created, location: @firstname }
      else
        format.html { render :new }
        format.json { render json: @firstname.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /firstnames/1
  # PATCH/PUT /firstnames/1.json
  def update
    respond_to do |format|
      if @firstname.update(firstname_params)
        format.html { redirect_to @firstname, notice: 'Firstname was successfully updated.' }
        format.json { render :show, status: :ok, location: @firstname }
      else
        format.html { render :edit }
        format.json { render json: @firstname.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /firstnames/1
  # DELETE /firstnames/1.json
  def destroy
    @firstname.destroy
    respond_to do |format|
      format.html { redirect_to firstnames_url, notice: 'Firstname was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_firstname
      @firstname = Firstname.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def firstname_params
      params.require(:firstname).permit(:language_id)
    end
end

app/helpers/firstnames_helper.rb
module FirstnamesHelper
end

app/views/firstnames/_form.html.erb
<%= form_with(model: firstname, local: true) do |form| %>
  <% if firstname.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(firstname.errors.count, "error") %> prohibited this firstname from being saved:</h2>

      <ul>
      <% firstname.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :language_id %>
    <%= form.text_field :language_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/firstnames/edit.html.erb
<h1>Editing Firstname</h1>

<%= render 'form', firstname: @firstname %>

<%= link_to 'Show', @firstname %> |
<%= link_to 'Back', firstnames_path %>

app/views/firstnames/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Firstnames</h1>

<table>
  <thead>
    <tr>
      <th>Language</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @firstnames.each do |firstname| %>
      <tr>
        <td><%= firstname.language %></td>
        <td><%= link_to 'Show', firstname %></td>
        <td><%= link_to 'Edit', edit_firstname_path(firstname) %></td>
        <td><%= link_to 'Destroy', firstname, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Firstname', new_firstname_path %>

app/views/firstnames/new.html.erb
<h1>New Firstname</h1>

<%= render 'form', firstname: @firstname %>

<%= link_to 'Back', firstnames_path %>

app/views/firstnames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Language:</strong>
  <%= @firstname.language %>
</p>

<%= link_to 'Edit', edit_firstname_path(@firstname) %> |
<%= link_to 'Back', firstnames_path %>