config/routes.rb
Rails.application.routes.draw do
  resources :firstnames
  resources :surnames
  resources :languages
  resources :cities
  resources :countries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/surname.rb
class Surname < ApplicationRecord
  belongs_to :language
end

app/controllers/surnames_controller.rb
class SurnamesController < ApplicationController
  before_action :set_surname, only: [:show, :edit, :update, :destroy]

  # GET /surnames
  # GET /surnames.json
  def index
    @surnames = Surname.all
  end

  # GET /surnames/1
  # GET /surnames/1.json
  def show
  end

  # GET /surnames/new
  def new
    @surname = Surname.new
  end

  # GET /surnames/1/edit
  def edit
  end

  # POST /surnames
  # POST /surnames.json
  def create
    @surname = Surname.new(surname_params)

    respond_to do |format|
      if @surname.save
        format.html { redirect_to @surname, notice: 'Surname was successfully created.' }
        format.json { render :show, status: :created, location: @surname }
      else
        format.html { render :new }
        format.json { render json: @surname.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surnames/1
  # PATCH/PUT /surnames/1.json
  def update
    respond_to do |format|
      if @surname.update(surname_params)
        format.html { redirect_to @surname, notice: 'Surname was successfully updated.' }
        format.json { render :show, status: :ok, location: @surname }
      else
        format.html { render :edit }
        format.json { render json: @surname.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surnames/1
  # DELETE /surnames/1.json
  def destroy
    @surname.destroy
    respond_to do |format|
      format.html { redirect_to surnames_url, notice: 'Surname was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_surname
      @surname = Surname.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def surname_params
      params.require(:surname).permit(:language_id)
    end
end

app/helpers/surnames_helper.rb
module SurnamesHelper
end

app/views/surnames/_form.html.erb
<%= form_with(model: surname, local: true) do |form| %>
  <% if surname.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(surname.errors.count, "error") %> prohibited this surname from being saved:</h2>

      <ul>
      <% surname.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :language_id %>
    <%= form.text_field :language_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/surnames/edit.html.erb
<h1>Editing Surname</h1>

<%= render 'form', surname: @surname %>

<%= link_to 'Show', @surname %> |
<%= link_to 'Back', surnames_path %>

app/views/surnames/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Surnames</h1>

<table>
  <thead>
    <tr>
      <th>Language</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surnames.each do |surname| %>
      <tr>
        <td><%= surname.language %></td>
        <td><%= link_to 'Show', surname %></td>
        <td><%= link_to 'Edit', edit_surname_path(surname) %></td>
        <td><%= link_to 'Destroy', surname, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Surname', new_surname_path %>

app/views/surnames/new.html.erb
<h1>New Surname</h1>

<%= render 'form', surname: @surname %>

<%= link_to 'Back', surnames_path %>

app/views/surnames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Language:</strong>
  <%= @surname.language %>
</p>

<%= link_to 'Edit', edit_surname_path(@surname) %> |
<%= link_to 'Back', surnames_path %>